image: barichello/elm:cp-swf

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

analyse:
  stage: build
  script:
    - elm-analyse

make:
  stage: build
  script:
    - elm make src/Main.elm --output=main.js --optimize
    # - uglifyjs main.js --compress sequences=true,conditionals=true,booleans=true --mangle --output main.js
  artifacts:
    paths:
      - main.js
      - index.html

pages:
  stage: deploy
  dependencies:
    - make
  script:
    - rm -f *.md
    - mkdir -p public
    - mv cp-swf-archive index.html main.js LICENSE public
    - git fetch
    - git checkout pages
  artifacts:
    paths:
      - public
