image: barichello/elm:cp-swf

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

analyse:
  stage: build
  script:
    - elm-analyse

make:
  stage: build
  script:
    - elm make src/Main.elm --output=main.js --optimize
    - uglifyjs main.js --compress sequences=true,conditionals=true,booleans=true --mangle --output main.js
  artifacts:
    paths:
      - main.js
      - index.html
      - main.css

pages:
  stage: deploy
  dependencies:
    - make
  script:
    - rm -f *.md
    - mkdir -p public ruffle
    - wget --output-document ruffle.zip https://github.com/ruffle-rs/ruffle/releases/download/nightly-2021-06-27/ruffle-nightly-2021_06_27-web-selfhosted.zip
    - unzip ruffle.zip -d ruffle
    - mv cp-swf-archive index.html main.js ports.js main.css ruffle public
    - tree -J public/cp-swf-archive > public/cp-swf-archive/archive.json
    - git fetch
    - git checkout pages
  artifacts:
    paths:
      - public
